ALTER TABLE distro
    ALTER COLUMN name TYPE VARCHAR(30),
    ALTER COLUMN homepage TYPE VARCHAR(255),
    ALTER COLUMN distrowatch_url TYPE VARCHAR(255),
    ALTER COLUMN image_url TYPE VARCHAR(255),
    ALTER COLUMN based_on TYPE VARCHAR(30),
    ALTER COLUMN release_date TYPE CHAR(10),
    ALTER COLUMN origin TYPE VARCHAR(50),
    ALTER COLUMN status TYPE VARCHAR(50);