spring.application.name=YetAnotherDistroChooser
server.port=8081

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.connection-timeout=20000

# Flyway configuration
spring.flyway.url=${SPRING_DATASOURCE_URL}
spring.flyway.user=${SPRING_DATASOURCE_USERNAME}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.baselineOnMigrate = true

# Profiles
#spring.profiles.active=test
#spring.profiles.active=load-test